### PR TITLE
add backup-support for the charging backend

### PR DESCRIPTION
**Pull request by wistefan**
Add support for automatically backing-up the data inside the charging-backend's filesystem to a gcs-bucket.

### CODE REVIEW

**Comment by dwendland** [comment]
Couldn't we put the image wistefan/gcs-folder-backup under FIWARE org? Might be also used in other FIWARE components in the future.

**Comment by jason-fox** [comment]
I agree with @dwendland - If it's part of a official FIWARE helm chart, then I think this image should be also officially from FIWARE and not from a private repo

**Comment by wistefan** [comment]
> I agree with @dwendland - If it's part of a official FIWARE helm chart, then I think this image should be also officially from FIWARE and not from a private repo

We can put it there. I only wanted to start somewhere.

**Comment by wistefan** [comment]
@dwendland @jason-fox Please see: https://github.com/FIWARE/copy-to-gcs/pull/5

**Comment by wistefan** [comment]
@dwendland I updated it. Please check again

**Review by dwendland — APPROVED** [review]
Ok

**Pull request merged**
