### PR TITLE
Value for config.js path . Solve issue iot agent version from version…

### PR DESCRIPTION
**Pull request by jorgesanmartin**
… 1.19

### CODE REVIEW

**Review by wistefan — APPROVED** [review]

**Comment by jorgesanmartin** [comment]
Any update for this issue? Do we need to do something from our side? We would like to have a new chart version to avoid the manual updates when we deploy the iotagents

**Comment by jorgesanmartin** [comment]
Please can you give me any feedback about the status of this pull request? is there any blocking issue for the approval?

**Comment by wistefan** [comment]
> Please can you give me any feedback about the status of this pull request? is there any blocking issue for the approval?

Sorry, I just forgot to merge it.

**Comment by jorgesanmartin** [comment]
It seems there is a problem with the merge. do we need to update anything?

**Pull request merged**
